version: 2.1

shell: /bin/bash -eo pipefail

parameters:
  run_commit_main:
    default: "run_if_on_main"
    type: enum
    enum: ["run_if_on_main", "run", "skip"]

  run_dev_delivery:
    default: false
    type: boolean

  run_prod_delivery:
    default: false
    type: boolean

  run_promote:
    default: false
    type: boolean
